//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand
    {
        public string Customer_Email { get; set; }
        public string Wharehouse_Name { get; set; }
        public int item_code { get; set; }
        public Nullable<int> demand_Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual item item { get; set; }
        public virtual Wharehouse Wharehouse { get; set; }
    }
}
